Agere\Module\Model\Module:
  type: entity
  table: module
  indexes:
    mnemo:
      columns: [ mnemo ]
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
    namespace:
     type: string
     length: 255
    mnemo:
      type: string
      length: 32
      unique: true
    hidden:
      type: integer
      length: 1
      default: '0'